apiVersion: v1
clusters:
- name: "k8s-vigilant-jepsen"
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1EVXhPVEV6TXpBd04xb1hEVE14TURVeE9URXpNekF3TjFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTlZBCm5uOXovZXNSckpaSzVtZlIvSGJoaE92eEVKWXlsK3hHN0lzZkc4SDlOekwwQzRMVEF6Y3o2bDdJOWRSMXJwaW4KSlRCTDA5M0FpQVNSNTVhV2VGRDVhN1NwaGhCWXJjekFoWktBTG5HMmFLZnp0czJZNVVLNHpKeTRxYWpRd2U2VwpHZzRWQ2pTUEs2cGhiTmFMZmdGRWc1OUw3RC8yeGhFTVJQa2FvVXNwN1pJdVYyZkJyM1VDZjZ1Wm9UREEwKy8rCkVLVGh0a29CQjV2NjFPbG95ZFpZRlVDdzBHQmVEK0NldVViWHVycVdhbHlNWDAvM1V2Z1h5alkxbk5uQWNMN2gKYW1UZXlmR245UWpUa0NjdWUxRWFXMExyVE5kOTA3MDlpdkkxVCtmMDJGYmNORDdRYW5uMWMycDVuNDUxZGJ0dApuUTJ5NWpMZWtGZWxiNHBLRXBjQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZKQ1hjWHEya2NBR2ZGU1NjSnc2YUdlZGZxaFpNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBZER5WHJrSkNpNDdPN2d0NnRYdDdDY0tKdHFpQ3VsbEdPMGRsU2lsSit0RFJlUFFIWApGKy9pZGtKVlorVWlCTmp3T3BlcE04ejM3N29FN3RwOW0veTYvazMxREVPSGd1aVRlV1Fndk83ei9Cd01lbjlhCnFPY084c3NaemxpeVl1aklqdEhPdXV3bEN1ZVdtVXNqYmFLOUlWQUFQQ20xazMwRy9MYmN4dUFsMGgwaVlEdHkKUUFJUjZLbmRjNTNIcXRZbWVlRVA5bzBuaC8xMm5iNWZYZWN4cmpRdlVzdmprVm1mVmFiY0pDem5HcTVmeWR3YQpSVGpldFZuWnF2by9mblhZMUNZamFZaXExd2tFWU5XZ3VwMWc2RDlBbmljbGRaUlNTWnN4cG5ybEx2dUsyUGxUCmIxaE1oc3VkUUpGZ0wrc2hsUXNjbTRsSDRVNjByMTI3M2RRTQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://0892b62f-1e15-4127-9ba7-8d2d68430721.api.k8s.fr-par.scw.cloud:6443
contexts:
- name: admin@k8s-vigilant-jepsen
  context:
    cluster: "k8s-vigilant-jepsen"
    user: k8s-vigilant-jepsen-admin
current-context: admin@k8s-vigilant-jepsen
kind: Config
preferences: {}
users:
- name: k8s-vigilant-jepsen-admin
  user:
    token: RuQ767Y8O1OJByDzRikctFasap9CiwzNHWOSS4GzfMC9eq2ssqX4K2Ek